# Generated by Django 4.1.3 on 2023-01-06 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0002_customer_addresses'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='terittory',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
