# Generated by Django 4.1.3 on 2023-01-08 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0003_address_terittory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='terittory',
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='terittory',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
