# Generated by Django 4.1.3 on 2023-01-17 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0005_rename_terittory_customeraddress_territory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='addresses',
            field=models.ManyToManyField(blank=True, through='Customers.CustomerAddress', to='Customers.address'),
        ),
        migrations.AlterUniqueTogether(
            name='customeraddress',
            unique_together={('customer', 'address')},
        ),
    ]
