# Generated by Django 4.1.3 on 2023-01-17 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0006_alter_customer_addresses_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'permissions': [('view_history', 'Can view history')]},
        ),
    ]
