# Generated by Django 4.1.3 on 2023-01-15 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0005_alter_order_timings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='timings',
            field=models.CharField(blank=True, choices=[('Evening', '12.00-18.00'), ('Night', '18.00-23.00'), ('Morning', '06.00-12.00')], max_length=255, null=True),
        ),
    ]
