# Generated by Django 4.1.3 on 2023-01-17 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0009_alter_order_timings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': [('cancel_order', 'Can cancel order')]},
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('F', 'Failed'), ('C', 'Complete'), ('P', 'Pending')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='timings',
            field=models.CharField(blank=True, choices=[('Night', '18.00-23.00'), ('Morning', '06.00-12.00'), ('Evening', '12.00-18.00')], max_length=255, null=True),
        ),
    ]
