# Generated by Django 4.1.3 on 2023-01-17 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0007_alter_customer_options'),
        ('Orders', '0012_alter_order_timings_alter_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='customer',
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Orders.payment'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='Customers.customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='timings',
            field=models.CharField(blank=True, choices=[('Morning', '06.00-12.00'), ('Night', '18.00-23.00'), ('Evening', '12.00-18.00')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('F', 'Failed'), ('C', 'Complete')], default='P', max_length=1),
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
