# Generated by Django 4.1.3 on 2023-01-17 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0013_remove_order_items_remove_payment_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='totalprice',
        ),
        migrations.AlterField(
            model_name='order',
            name='timings',
            field=models.CharField(blank=True, choices=[('Night', '18.00-23.00'), ('Evening', '12.00-18.00'), ('Morning', '06.00-12.00')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('C', 'Complete'), ('F', 'Failed'), ('P', 'Pending')], default='P', max_length=1),
        ),
    ]
