# Generated by Django 4.1.3 on 2023-01-17 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0016_alter_payment_status_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Orders.payment'),
        ),
        migrations.AlterField(
            model_name='order',
            name='timings',
            field=models.CharField(blank=True, choices=[('Morning', '06.00-12.00'), ('Evening', '12.00-18.00'), ('Night', '18.00-23.00')], max_length=255, null=True),
        ),
    ]
