# Generated by Django 4.1.3 on 2023-01-17 12:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0009_cart_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
